apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth-depl.yaml
  - tickets-depl.yaml
  - orders-depl.yaml
  - payments-depl.yaml
  - expiration-depl.yaml
  - client-depl.yaml
